// This file will be auto-generated by Supabase CLI, but for now we'll define basic types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      people: {
        Row: {
          id: string;
          name: string;
          email: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      conferences: {
        Row: {
          id: string;
          name: string;
          location: string;
          category: string;
          price: number;
          currency: string;
          office_id: string | null;
          assigned_to: string | null;
          start_date: string | null;
          end_date: string | null;
          event_link: string | null;
          notes: string | null;
          status: "Interested" | "Planned" | "Booked" | "Attended" | null;
          reason_to_go: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          location: string;
          category: string;
          price: number;
          currency?: string;
          office_id?: string | null;
          assigned_to?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          event_link?: string | null;
          notes?: string | null;
          status?: "Interested" | "Planned" | "Booked" | "Attended" | null;
          reason_to_go?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          location?: string;
          category?: string;
          price?: number;
          currency?: string;
          office_id?: string | null;
          assigned_to?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          event_link?: string | null;
          notes?: string | null;
          status?: "Interested" | "Planned" | "Booked" | "Attended" | null;
          reason_to_go?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ratings: {
        Row: {
          id: string;
          conference_id: string;
          accessibility_rating: number | null;
          skill_improvement_rating: number | null;
          finding_partners_rating: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conference_id: string;
          accessibility_rating?: number | null;
          skill_improvement_rating?: number | null;
          finding_partners_rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          conference_id?: string;
          accessibility_rating?: number | null;
          skill_improvement_rating?: number | null;
          finding_partners_rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
